version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4250:4250"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
